name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  job-name:
    description: 'Name of GA job'
    required: true
    default: 'nada'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'